// Code generated by goctl. DO NOT EDIT.
package types

import "e_tab_be/internal/model"

type Tab struct {
	Url   string `json:"url"`
	Title string `json:"title"`
}

func (t *Tab) ToModel(domain string) *model.Tab{
	return &model.Tab{
		Url:         t.Url,
		Title:       t.Title,
		Domain:      domain,
	}
}

type Request struct {
	Tabs []*Tab `json:"tabs"`
}

type Response struct {
	Message string `json:"message"`
}
